version: 0.2

phases:

  install:

    runtime-versions:

      dotnet: 6.0

  pre_build:

    commands:

      - dotnet restore pc1.csproj

  build:

    commands:

      - dotnet build pc1.csproj

  post_build:

    commands:

      - dotnet publish -c Release -o ./app/ pc1.csproj

artifacts:

  files:

    - '**/*'
